from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Subject(models.Model):
	name = models.CharField(max_length=100)
	total = models.IntegerField(default=0)
	absent = models.IntegerField(default=0)
	att_perc= models.FloatField(default=100.0)
	user = models.ForeignKey(User, on_delete=models.CASCADE)

class Sgpa(models.Model):
   credit1 = models.IntegerField(default=0)
   credit2 = models.IntegerField(default=0)
   credit3 = models.IntegerField(default=0)
   credit4 = models.IntegerField(default=0)
   credit5 = models.IntegerField(default=0)
   credit6 = models.IntegerField(default=0)
   credit7 = models.IntegerField(default=0)
   credit8 = models.IntegerField(default=0)
   grade_point1 = models.IntegerField(default=0)
   grade_point2 = models.IntegerField(default=0)
   grade_point3 = models.IntegerField(default=0)
   grade_point4 = models.IntegerField(default=0)
   grade_point5 = models.IntegerField(default=0)
   grade_point6 = models.IntegerField(default=0)
   grade_point7 = models.IntegerField(default=0)
   grade_point8 = models.IntegerField(default=0)
   credit_pt1 = models.IntegerField(default=0) 
   credit_pt2 = models.IntegerField(default=0)  
   credit_pt3 = models.IntegerField(default=0)  
   credit_pt4 = models.IntegerField(default=0)  
   credit_pt5 = models.IntegerField(default=0)  
   credit_pt6 = models.IntegerField(default=0)
   credit_pt7 = models.IntegerField(default=0)
   credit_pt8 = models.IntegerField(default=0)
   tot_cp = models.IntegerField(default=0)
   tot_c = models.IntegerField(default=0) 
   tot_sgpa = models.IntegerField(default=0)
   percent = models.IntegerField(default=0) 


class Cgpa(models.Model):
   c1 = models.IntegerField(default=0)
   c2 = models.IntegerField(default=0)
   c3 = models.IntegerField(default=0)
   c4 = models.IntegerField(default=0)
   c5 = models.IntegerField(default=0)
   c6 = models.IntegerField(default=0) 
   c7 = models.IntegerField(default=0)
   c8 = models.IntegerField(default=0)
   sg1 = models.IntegerField(default=0)
   sg2 = models.IntegerField(default=0)
   sg3 = models.IntegerField(default=0)
   sg4 = models.IntegerField(default=0)
   sg5 = models.IntegerField(default=0)
   sg6 = models.IntegerField(default=0) 
   sg7 = models.IntegerField(default=0)
   sg8 = models.IntegerField(default=0)
   total_cg = models.IntegerField(default=0)
   total_c = models.IntegerField(default=0)
   total = models.IntegerField(default=0)
   percentage = models.IntegerField(default=0)  
    
