# Generated by Django 2.1.1 on 2018-10-09 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cgpa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1', models.IntegerField(default=0)),
                ('c2', models.IntegerField(default=0)),
                ('c3', models.IntegerField(default=0)),
                ('c4', models.IntegerField(default=0)),
                ('c5', models.IntegerField(default=0)),
                ('c6', models.IntegerField(default=0)),
                ('c7', models.IntegerField(default=0)),
                ('c8', models.IntegerField(default=0)),
                ('sg1', models.IntegerField(default=0)),
                ('sg2', models.IntegerField(default=0)),
                ('sg3', models.IntegerField(default=0)),
                ('sg4', models.IntegerField(default=0)),
                ('sg5', models.IntegerField(default=0)),
                ('sg6', models.IntegerField(default=0)),
                ('sg7', models.IntegerField(default=0)),
                ('sg8', models.IntegerField(default=0)),
                ('total_cg', models.IntegerField(default=0)),
                ('total_c', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('percentage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sgpa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit1', models.IntegerField(default=0)),
                ('credit2', models.IntegerField(default=0)),
                ('credit3', models.IntegerField(default=0)),
                ('credit4', models.IntegerField(default=0)),
                ('credit5', models.IntegerField(default=0)),
                ('credit6', models.IntegerField(default=0)),
                ('credit7', models.IntegerField(default=0)),
                ('credit8', models.IntegerField(default=0)),
                ('grade_point1', models.IntegerField(default=0)),
                ('grade_point2', models.IntegerField(default=0)),
                ('grade_point3', models.IntegerField(default=0)),
                ('grade_point4', models.IntegerField(default=0)),
                ('grade_point5', models.IntegerField(default=0)),
                ('grade_point6', models.IntegerField(default=0)),
                ('grade_point7', models.IntegerField(default=0)),
                ('grade_point8', models.IntegerField(default=0)),
                ('credit_pt1', models.IntegerField(default=0)),
                ('credit_pt2', models.IntegerField(default=0)),
                ('credit_pt3', models.IntegerField(default=0)),
                ('credit_pt4', models.IntegerField(default=0)),
                ('credit_pt5', models.IntegerField(default=0)),
                ('credit_pt6', models.IntegerField(default=0)),
                ('credit_pt7', models.IntegerField(default=0)),
                ('credit_pt8', models.IntegerField(default=0)),
                ('tot_cp', models.IntegerField(default=0)),
                ('tot_c', models.IntegerField(default=0)),
                ('tot_sgpa', models.IntegerField(default=0)),
                ('percent', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='number',
        ),
        migrations.AddField(
            model_name='subject',
            name='absent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='att_perc',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='subject',
            name='name',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
